# Generated by Django 4.0.4 on 2022-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cake name')),
                ('about', models.TextField(verbose_name='Cake about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Cake img')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
            },
        ),
    ]
