# Generated by Django 4.0.4 on 2022-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='About name')),
                ('about', models.TextField(verbose_name='About about')),
                ('img', models.ImageField(upload_to='media', verbose_name='About Img')),
            ],
        ),
    ]
